apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: $USER
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
    hostSubnetLength: 9
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
    hostSubnetLength: 9
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceCIDR: 172.30.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
  type: OpenShiftSDN
platform:
  aws:
    region: us-west-1
pullSecret: $PullSecret
sshKey: |
  $SSHPublicKey
